#!/bin/bash

set -e

if [ $# -eq 0 ]
  then
    echo -e "\nUsage: publish-to-flathub <tag>\n"
    exit 1
fi

# Get the commit that the requested tag points to.
commit=$(git rev-list -n 1 $1)

echo -e "\nPublishing version $1:\n"

#
# Copy Flatpak and appstream metadata.
#
printf '  • Copying Flatpak and appstream metadata…'

cp ind.ie.Gnomit.json ../flathub
cp data/ind.ie.Gnomit.appdata.xml.in ../flathub/ind.ie.Gnomit.appdata.xml
cp data/ind.ie.Gnomit.desktop.in ../flathub/ind.ie.Gnomit.desktop

printf ' done ✓\n'

#
# Update manifest with the tag and commit instead of
# of the local repository path.
#
printf '    Updating manifest with commit of tag $1…'

sed -i -e "s/                    \"url\" : \"file:\/\/\/home\/aral\/ind.ie\/gnomit\/gjs\"/                    \"tag\" : "$1",\n                    \"commit\" : \"$commit\"/" ../flathub/ind.ie.Gnomit.json

printf ' done ✓\n'

# for now
exit

#
# Commit the version
#
# TODO

#
# Push to Flathub
#
# TODO

