#!/bin/bash

set -e

if [ $# -eq 0 ]
  then
    echo -e "\nUsage: publish-to-flathub <tag>\n"
    exit 1
fi

#
# Runs command in requested directory and restores the working directory at the end.
# Usage: run <directory> "<command>"
#
runIn(){
	pushd $1 >/dev/null
	eval $2
	popd >/dev/null
}

# Get the commit that the requested tag points to.
commit=$(git rev-list -n 1 $1)

echo -e "\nPublishing version $1 to Flathub…\n"

#
# Copy Flatpak and appstream metadata.
#
printf '  • Copying Flatpak and appstream metadata…'

cp ind.ie.Gnomit.json ../flathub
cp data/ind.ie.Gnomit.appdata.xml.in ../flathub/ind.ie.Gnomit.appdata.xml
cp data/ind.ie.Gnomit.desktop.in ../flathub/ind.ie.Gnomit.desktop

printf ' done ✓\n'

#
# Update manifest with the tag and commit instead of
# of the local repository path.
#
printf "  • Updating manifest with commit of tag $1…"

sed -i -e "s/                    \"url\" : \"file:\/\/\/home\/aral\/ind.ie\/gnomit\/gjs\"/                    \"url\" : \"https:\/\/source.ind.ie\/gnome\/gnomit\/gjs.git\",\n                    \"tag\" : \"$1\",\n                    \"commit\" : \"$commit\"/" ../flathub/ind.ie.Gnomit.json

printf ' done ✓\n'

#
# Commit the version
#
printf "  • Committing version $1…"

runIn ../flathub "git add --all"
runIn ../flathub "git commit -m \"Version $1\""

printf ' done ✓\n'

#
# Push to Flathub
#
printf "  • Pushing version $1 to Flathub…"

# runIn ../flathub git push

printf ' done ✓\n'

# All done! :)
echo -e "\nDone ✓\n"
